#############################################################################
# Makefile for building: dist/aquamatcontrol
# Generated by qmake (2.01a) (Qt 4.6.2) on: ?r. kwi 20 20:08:24 2011
# Project:  aquamatcontrol.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile aquamatcontrol.pro
#############################################################################

####### Compiler, tools and options

CC            = @echo compiling $< && gcc
CXX           = @echo compiling $< && g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc -I/usr/local/include -Iobj -Isrc
LINK          = @echo linking $@ && g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib/qt4
LIBS          = $(SUBLIBS)  -L/usr/lib/qt4 -lfancywidgets -lqextserialport -lQtGui -L/usr/lib/qt4 -L/usr/X11R6/lib -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/aboutDialog.cpp \
		src/codeUpdateThread.cpp \
		src/codeUpdateDialog.cpp \
		src/codeUpdate.cpp \
		src/comboBoxOuts.cpp \
		src/comboBoxWeekDay.cpp \
		src/command.cpp \
		src/commandProcessor.cpp \
		src/main.cpp \
		src/mainWindow.cpp \
		src/mainWindowAbout.cpp \
		src/mainWindowUpdate.cpp \
		src/outDisplay.cpp \
		src/pwmSettings.cpp \
		src/outSettings.cpp \
		src/refreshThread.cpp \
		src/tempDisplay.cpp \
		src/temperature.cpp \
		src/tempSettings.cpp \
		src/timersSettings.cpp \
		src/timersvSettings.cpp \
		src/comboBoxQButtons.cpp \
		src/timersSecSettings.cpp \
		src/sunScenario.cpp \
		src/controlComponent.cpp \
		src/comboBoxPwms.cpp obj/moc_aboutDialog.cpp \
		obj/moc_codeUpdateThread.cpp \
		obj/moc_codeUpdateDialog.cpp \
		obj/moc_comboBoxOuts.cpp \
		obj/moc_comboBoxWeekDay.cpp \
		obj/moc_commandProcessor.cpp \
		obj/moc_mainWindow.cpp \
		obj/moc_outDisplay.cpp \
		obj/moc_outSettings.cpp \
		obj/moc_refreshThread.cpp \
		obj/moc_tempDisplay.cpp \
		obj/moc_tempSettings.cpp \
		obj/moc_timersSettings.cpp \
		obj/moc_timersvSettings.cpp \
		obj/moc_comboBoxQButtons.cpp \
		obj/moc_pwmSettings.cpp \
		obj/moc_sunScenario.cpp \
		obj/moc_timersSecSettings.cpp \
		obj/moc_controlComponent.cpp \
		obj/moc_comboBoxPwms.cpp \
		resources/qrc_aquamatcontrol.cpp
OBJECTS       = obj/aboutDialog.o \
		obj/codeUpdateThread.o \
		obj/codeUpdateDialog.o \
		obj/codeUpdate.o \
		obj/comboBoxOuts.o \
		obj/comboBoxWeekDay.o \
		obj/command.o \
		obj/commandProcessor.o \
		obj/main.o \
		obj/mainWindow.o \
		obj/mainWindowAbout.o \
		obj/mainWindowUpdate.o \
		obj/outDisplay.o \
		obj/pwmSettings.o \
		obj/outSettings.o \
		obj/refreshThread.o \
		obj/tempDisplay.o \
		obj/temperature.o \
		obj/tempSettings.o \
		obj/timersSettings.o \
		obj/timersvSettings.o \
		obj/comboBoxQButtons.o \
		obj/timersSecSettings.o \
		obj/sunScenario.o \
		obj/controlComponent.o \
		obj/comboBoxPwms.o \
		obj/moc_aboutDialog.o \
		obj/moc_codeUpdateThread.o \
		obj/moc_codeUpdateDialog.o \
		obj/moc_comboBoxOuts.o \
		obj/moc_comboBoxWeekDay.o \
		obj/moc_commandProcessor.o \
		obj/moc_mainWindow.o \
		obj/moc_outDisplay.o \
		obj/moc_outSettings.o \
		obj/moc_refreshThread.o \
		obj/moc_tempDisplay.o \
		obj/moc_tempSettings.o \
		obj/moc_timersSettings.o \
		obj/moc_timersvSettings.o \
		obj/moc_comboBoxQButtons.o \
		obj/moc_pwmSettings.o \
		obj/moc_sunScenario.o \
		obj/moc_timersSecSettings.o \
		obj/moc_controlComponent.o \
		obj/moc_comboBoxPwms.o \
		obj/qrc_aquamatcontrol.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/silent.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		aquamatcontrol.pro
QMAKE_TARGET  = aquamatcontrol
DESTDIR       = dist/
TARGET        = dist/aquamatcontrol

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): src/ui_aboutDialog.h src/ui_mainWindow.h src/ui_outSettings.h src/ui_tempSettings.h src/ui_timersSettings.h src/ui_timersvSettings.h src/ui_codeUpdateDialog.h src/ui_pwmSettings.h src/ui_timersSecSettings.h src/ui_sunScenario.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) dist/ || $(MKDIR) dist/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: aquamatcontrol.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/silent.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/libQtGui.prl \
		/usr/lib/qt4/libQtCore.prl
	$(QMAKE) -unix -o Makefile aquamatcontrol.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/silent.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/libQtGui.prl:
/usr/lib/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile aquamatcontrol.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/aquamatcontrol1.0.0 || $(MKDIR) obj/aquamatcontrol1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/aquamatcontrol1.0.0/ && $(COPY_FILE) --parents src/aboutDialog.h src/codeUpdateThread.h src/codeUpdateDialog.h src/codeUpdate.h src/comboBoxOuts.h src/comboBoxWeekDay.h src/command.h src/commandProcessor.h src/commandsDefs.h src/commonDefs.h src/main.h src/mainWindow.h src/outDisplay.h src/outSettings.h src/refreshThread.h src/tempDisplay.h src/temperature.h src/tempSettings.h src/timersSettings.h src/timersvSettings.h src/comboBoxQButtons.h src/pwmSettings.h src/sunScenario.h src/timersSecSettings.h src/controlComponent.h src/comboBoxPwms.h obj/aquamatcontrol1.0.0/ && $(COPY_FILE) --parents resources/aquamatcontrol.qrc obj/aquamatcontrol1.0.0/ && $(COPY_FILE) --parents src/aboutDialog.cpp src/codeUpdateThread.cpp src/codeUpdateDialog.cpp src/codeUpdate.cpp src/comboBoxOuts.cpp src/comboBoxWeekDay.cpp src/command.cpp src/commandProcessor.cpp src/main.cpp src/mainWindow.cpp src/mainWindowAbout.cpp src/mainWindowUpdate.cpp src/outDisplay.cpp src/pwmSettings.cpp src/outSettings.cpp src/refreshThread.cpp src/tempDisplay.cpp src/temperature.cpp src/tempSettings.cpp src/timersSettings.cpp src/timersvSettings.cpp src/comboBoxQButtons.cpp src/timersSecSettings.cpp src/sunScenario.cpp src/controlComponent.cpp src/comboBoxPwms.cpp obj/aquamatcontrol1.0.0/ && $(COPY_FILE) --parents src/aboutDialog.ui src/mainWindow.ui src/outSettings.ui src/tempSettings.ui src/timersSettings.ui src/timersvSettings.ui src/codeUpdateDialog.ui src/pwmSettings.ui src/timersSecSettings.ui src/sunScenario.ui obj/aquamatcontrol1.0.0/ && (cd `dirname obj/aquamatcontrol1.0.0` && $(TAR) aquamatcontrol1.0.0.tar aquamatcontrol1.0.0 && $(COMPRESS) aquamatcontrol1.0.0.tar) && $(MOVE) `dirname obj/aquamatcontrol1.0.0`/aquamatcontrol1.0.0.tar.gz . && $(DEL_FILE) -r obj/aquamatcontrol1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


docs: FORCE
	doxygen Doxyfile

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: obj/moc_aboutDialog.cpp obj/moc_codeUpdateThread.cpp obj/moc_codeUpdateDialog.cpp obj/moc_comboBoxOuts.cpp obj/moc_comboBoxWeekDay.cpp obj/moc_commandProcessor.cpp obj/moc_mainWindow.cpp obj/moc_outDisplay.cpp obj/moc_outSettings.cpp obj/moc_refreshThread.cpp obj/moc_tempDisplay.cpp obj/moc_tempSettings.cpp obj/moc_timersSettings.cpp obj/moc_timersvSettings.cpp obj/moc_comboBoxQButtons.cpp obj/moc_pwmSettings.cpp obj/moc_sunScenario.cpp obj/moc_timersSecSettings.cpp obj/moc_controlComponent.cpp obj/moc_comboBoxPwms.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) obj/moc_aboutDialog.cpp obj/moc_codeUpdateThread.cpp obj/moc_codeUpdateDialog.cpp obj/moc_comboBoxOuts.cpp obj/moc_comboBoxWeekDay.cpp obj/moc_commandProcessor.cpp obj/moc_mainWindow.cpp obj/moc_outDisplay.cpp obj/moc_outSettings.cpp obj/moc_refreshThread.cpp obj/moc_tempDisplay.cpp obj/moc_tempSettings.cpp obj/moc_timersSettings.cpp obj/moc_timersvSettings.cpp obj/moc_comboBoxQButtons.cpp obj/moc_pwmSettings.cpp obj/moc_sunScenario.cpp obj/moc_timersSecSettings.cpp obj/moc_controlComponent.cpp obj/moc_comboBoxPwms.cpp
obj/moc_aboutDialog.cpp: src/ui_aboutDialog.h \
		src/aboutDialog.h
	@echo moc src/aboutDialog.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/aboutDialog.h -o obj/moc_aboutDialog.cpp

obj/moc_codeUpdateThread.cpp: src/codeUpdate.h \
		src/codeUpdateThread.h
	@echo moc src/codeUpdateThread.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/codeUpdateThread.h -o obj/moc_codeUpdateThread.cpp

obj/moc_codeUpdateDialog.cpp: src/ui_codeUpdateDialog.h \
		src/codeUpdateDialog.h
	@echo moc src/codeUpdateDialog.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/codeUpdateDialog.h -o obj/moc_codeUpdateDialog.cpp

obj/moc_comboBoxOuts.cpp: src/commonDefs.h \
		src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h \
		src/comboBoxOuts.h
	@echo moc src/comboBoxOuts.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/comboBoxOuts.h -o obj/moc_comboBoxOuts.cpp

obj/moc_comboBoxWeekDay.cpp: src/comboBoxWeekDay.h
	@echo moc src/comboBoxWeekDay.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/comboBoxWeekDay.h -o obj/moc_comboBoxWeekDay.cpp

obj/moc_commandProcessor.cpp: src/commandsDefs.h \
		src/command.h \
		src/commandProcessor.h
	@echo moc src/commandProcessor.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/commandProcessor.h -o obj/moc_commandProcessor.cpp

obj/moc_mainWindow.cpp: src/ui_mainWindow.h \
		src/aboutDialog.h \
		src/ui_aboutDialog.h \
		src/commandProcessor.h \
		src/commandsDefs.h \
		src/command.h \
		src/tempDisplay.h \
		src/temperature.h \
		src/commonDefs.h \
		src/outDisplay.h \
		src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h \
		src/pwmSettings.h \
		src/ui_pwmSettings.h \
		src/tempSettings.h \
		src/ui_tempSettings.h \
		src/comboBoxOuts.h \
		src/main.h \
		src/timersSettings.h \
		src/ui_timersSettings.h \
		src/comboBoxWeekDay.h \
		src/timersvSettings.h \
		src/ui_timersvSettings.h \
		src/timersSecSettings.h \
		src/ui_timersSecSettings.h \
		src/codeUpdate.h \
		src/codeUpdateDialog.h \
		src/ui_codeUpdateDialog.h \
		src/codeUpdateThread.h \
		src/sunScenario.h \
		src/controlComponent.h \
		src/ui_sunScenario.h \
		src/comboBoxPwms.h \
		src/mainWindow.h
	@echo moc src/mainWindow.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/mainWindow.h -o obj/moc_mainWindow.cpp

obj/moc_outDisplay.cpp: src/outDisplay.h
	@echo moc src/outDisplay.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/outDisplay.h -o obj/moc_outDisplay.cpp

obj/moc_outSettings.cpp: src/ui_outSettings.h \
		src/comboBoxQButtons.h \
		src/commonDefs.h \
		src/outSettings.h
	@echo moc src/outSettings.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/outSettings.h -o obj/moc_outSettings.cpp

obj/moc_refreshThread.cpp: src/codeUpdate.h \
		src/refreshThread.h
	@echo moc src/refreshThread.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/refreshThread.h -o obj/moc_refreshThread.cpp

obj/moc_tempDisplay.cpp: src/temperature.h \
		src/commonDefs.h \
		src/tempDisplay.h
	@echo moc src/tempDisplay.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/tempDisplay.h -o obj/moc_tempDisplay.cpp

obj/moc_tempSettings.cpp: src/temperature.h \
		src/commonDefs.h \
		src/ui_tempSettings.h \
		src/comboBoxOuts.h \
		src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h \
		src/main.h \
		src/tempSettings.h
	@echo moc src/tempSettings.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/tempSettings.h -o obj/moc_tempSettings.cpp

obj/moc_timersSettings.cpp: src/ui_timersSettings.h \
		src/comboBoxWeekDay.h \
		src/comboBoxOuts.h \
		src/commonDefs.h \
		src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h \
		src/timersSettings.h
	@echo moc src/timersSettings.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/timersSettings.h -o obj/moc_timersSettings.cpp

obj/moc_timersvSettings.cpp: src/ui_timersvSettings.h \
		src/comboBoxOuts.h \
		src/commonDefs.h \
		src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h \
		src/timersvSettings.h
	@echo moc src/timersvSettings.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/timersvSettings.h -o obj/moc_timersvSettings.cpp

obj/moc_comboBoxQButtons.cpp: src/commonDefs.h \
		src/comboBoxQButtons.h
	@echo moc src/comboBoxQButtons.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/comboBoxQButtons.h -o obj/moc_comboBoxQButtons.cpp

obj/moc_pwmSettings.cpp: src/ui_pwmSettings.h \
		src/pwmSettings.h
	@echo moc src/pwmSettings.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/pwmSettings.h -o obj/moc_pwmSettings.cpp

obj/moc_sunScenario.cpp: src/controlComponent.h \
		src/ui_sunScenario.h \
		src/comboBoxPwms.h \
		src/commonDefs.h \
		src/pwmSettings.h \
		src/ui_pwmSettings.h \
		src/sunScenario.h
	@echo moc src/sunScenario.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/sunScenario.h -o obj/moc_sunScenario.cpp

obj/moc_timersSecSettings.cpp: src/ui_timersSecSettings.h \
		src/comboBoxWeekDay.h \
		src/comboBoxOuts.h \
		src/commonDefs.h \
		src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h \
		src/timersSecSettings.h
	@echo moc src/timersSecSettings.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/timersSecSettings.h -o obj/moc_timersSecSettings.cpp

obj/moc_controlComponent.cpp: src/controlComponent.h
	@echo moc src/controlComponent.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/controlComponent.h -o obj/moc_controlComponent.cpp

obj/moc_comboBoxPwms.cpp: src/commonDefs.h \
		src/pwmSettings.h \
		src/ui_pwmSettings.h \
		src/comboBoxPwms.h
	@echo moc src/comboBoxPwms.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/comboBoxPwms.h -o obj/moc_comboBoxPwms.cpp

compiler_rcc_make_all: resources/qrc_aquamatcontrol.cpp
compiler_rcc_clean:
	-$(DEL_FILE) resources/qrc_aquamatcontrol.cpp
resources/qrc_aquamatcontrol.cpp: resources/aquamatcontrol.qrc \
		resources/sunScenario.png \
		resources/sunScenario.png \
		resources/top_off.png \
		resources/app_icon.ico \
		resources/logocontrol.png \
		resources/logocontrol2.png
	@echo rcc resources/aquamatcontrol.qrc && /usr/bin/rcc -name aquamatcontrol resources/aquamatcontrol.qrc -o resources/qrc_aquamatcontrol.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: src/ui_aboutDialog.h src/ui_mainWindow.h src/ui_outSettings.h src/ui_tempSettings.h src/ui_timersSettings.h src/ui_timersvSettings.h src/ui_codeUpdateDialog.h src/ui_pwmSettings.h src/ui_timersSecSettings.h src/ui_sunScenario.h
compiler_uic_clean:
	-$(DEL_FILE) src/ui_aboutDialog.h src/ui_mainWindow.h src/ui_outSettings.h src/ui_tempSettings.h src/ui_timersSettings.h src/ui_timersvSettings.h src/ui_codeUpdateDialog.h src/ui_pwmSettings.h src/ui_timersSecSettings.h src/ui_sunScenario.h
src/ui_aboutDialog.h: src/aboutDialog.ui
	@echo uic src/aboutDialog.ui && /usr/bin/uic src/aboutDialog.ui -o src/ui_aboutDialog.h

src/ui_mainWindow.h: src/mainWindow.ui
	@echo uic src/mainWindow.ui && /usr/bin/uic src/mainWindow.ui -o src/ui_mainWindow.h

src/ui_outSettings.h: src/outSettings.ui
	@echo uic src/outSettings.ui && /usr/bin/uic src/outSettings.ui -o src/ui_outSettings.h

src/ui_tempSettings.h: src/tempSettings.ui
	@echo uic src/tempSettings.ui && /usr/bin/uic src/tempSettings.ui -o src/ui_tempSettings.h

src/ui_timersSettings.h: src/timersSettings.ui
	@echo uic src/timersSettings.ui && /usr/bin/uic src/timersSettings.ui -o src/ui_timersSettings.h

src/ui_timersvSettings.h: src/timersvSettings.ui
	@echo uic src/timersvSettings.ui && /usr/bin/uic src/timersvSettings.ui -o src/ui_timersvSettings.h

src/ui_codeUpdateDialog.h: src/codeUpdateDialog.ui
	@echo uic src/codeUpdateDialog.ui && /usr/bin/uic src/codeUpdateDialog.ui -o src/ui_codeUpdateDialog.h

src/ui_pwmSettings.h: src/pwmSettings.ui
	@echo uic src/pwmSettings.ui && /usr/bin/uic src/pwmSettings.ui -o src/ui_pwmSettings.h

src/ui_timersSecSettings.h: src/timersSecSettings.ui
	@echo uic src/timersSecSettings.ui && /usr/bin/uic src/timersSecSettings.ui -o src/ui_timersSecSettings.h

src/ui_sunScenario.h: src/sunScenario.ui
	@echo uic src/sunScenario.ui && /usr/bin/uic src/sunScenario.ui -o src/ui_sunScenario.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

obj/aboutDialog.o: src/aboutDialog.cpp src/aboutDialog.h \
		src/ui_aboutDialog.h \
		src/main.h \
		src/commonDefs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/aboutDialog.o src/aboutDialog.cpp

obj/codeUpdateThread.o: src/codeUpdateThread.cpp src/codeUpdateThread.h \
		src/codeUpdate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/codeUpdateThread.o src/codeUpdateThread.cpp

obj/codeUpdateDialog.o: src/codeUpdateDialog.cpp src/codeUpdateDialog.h \
		src/ui_codeUpdateDialog.h \
		src/main.h \
		src/commonDefs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/codeUpdateDialog.o src/codeUpdateDialog.cpp

obj/codeUpdate.o: src/codeUpdate.cpp src/codeUpdate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/codeUpdate.o src/codeUpdate.cpp

obj/comboBoxOuts.o: src/comboBoxOuts.cpp src/comboBoxOuts.h \
		src/commonDefs.h \
		src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/comboBoxOuts.o src/comboBoxOuts.cpp

obj/comboBoxWeekDay.o: src/comboBoxWeekDay.cpp src/comboBoxWeekDay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/comboBoxWeekDay.o src/comboBoxWeekDay.cpp

obj/command.o: src/command.cpp src/command.h \
		src/commandsDefs.h \
		src/commonDefs.h \
		src/sunScenario.h \
		src/controlComponent.h \
		src/ui_sunScenario.h \
		src/comboBoxPwms.h \
		src/pwmSettings.h \
		src/ui_pwmSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/command.o src/command.cpp

obj/commandProcessor.o: src/commandProcessor.cpp src/commandProcessor.h \
		src/commandsDefs.h \
		src/command.h \
		src/mainWindow.h \
		src/ui_mainWindow.h \
		src/aboutDialog.h \
		src/ui_aboutDialog.h \
		src/tempDisplay.h \
		src/temperature.h \
		src/commonDefs.h \
		src/outDisplay.h \
		src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h \
		src/pwmSettings.h \
		src/ui_pwmSettings.h \
		src/tempSettings.h \
		src/ui_tempSettings.h \
		src/comboBoxOuts.h \
		src/main.h \
		src/timersSettings.h \
		src/ui_timersSettings.h \
		src/comboBoxWeekDay.h \
		src/timersvSettings.h \
		src/ui_timersvSettings.h \
		src/timersSecSettings.h \
		src/ui_timersSecSettings.h \
		src/codeUpdate.h \
		src/codeUpdateDialog.h \
		src/ui_codeUpdateDialog.h \
		src/codeUpdateThread.h \
		src/sunScenario.h \
		src/controlComponent.h \
		src/ui_sunScenario.h \
		src/comboBoxPwms.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/commandProcessor.o src/commandProcessor.cpp

obj/main.o: src/main.cpp src/mainWindow.h \
		src/ui_mainWindow.h \
		src/aboutDialog.h \
		src/ui_aboutDialog.h \
		src/commandProcessor.h \
		src/commandsDefs.h \
		src/command.h \
		src/tempDisplay.h \
		src/temperature.h \
		src/commonDefs.h \
		src/outDisplay.h \
		src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h \
		src/pwmSettings.h \
		src/ui_pwmSettings.h \
		src/tempSettings.h \
		src/ui_tempSettings.h \
		src/comboBoxOuts.h \
		src/main.h \
		src/timersSettings.h \
		src/ui_timersSettings.h \
		src/comboBoxWeekDay.h \
		src/timersvSettings.h \
		src/ui_timersvSettings.h \
		src/timersSecSettings.h \
		src/ui_timersSecSettings.h \
		src/codeUpdate.h \
		src/codeUpdateDialog.h \
		src/ui_codeUpdateDialog.h \
		src/codeUpdateThread.h \
		src/sunScenario.h \
		src/controlComponent.h \
		src/ui_sunScenario.h \
		src/comboBoxPwms.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/mainWindow.o: src/mainWindow.cpp src/mainWindow.h \
		src/ui_mainWindow.h \
		src/aboutDialog.h \
		src/ui_aboutDialog.h \
		src/commandProcessor.h \
		src/commandsDefs.h \
		src/command.h \
		src/tempDisplay.h \
		src/temperature.h \
		src/commonDefs.h \
		src/outDisplay.h \
		src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h \
		src/pwmSettings.h \
		src/ui_pwmSettings.h \
		src/tempSettings.h \
		src/ui_tempSettings.h \
		src/comboBoxOuts.h \
		src/main.h \
		src/timersSettings.h \
		src/ui_timersSettings.h \
		src/comboBoxWeekDay.h \
		src/timersvSettings.h \
		src/ui_timersvSettings.h \
		src/timersSecSettings.h \
		src/ui_timersSecSettings.h \
		src/codeUpdate.h \
		src/codeUpdateDialog.h \
		src/ui_codeUpdateDialog.h \
		src/codeUpdateThread.h \
		src/sunScenario.h \
		src/controlComponent.h \
		src/ui_sunScenario.h \
		src/comboBoxPwms.h \
		src/processingTemp.cpp \
		src/processingTime.cpp \
		src/processingPwm.cpp \
		src/processingAlarm.cpp \
		src/processingOut.cpp \
		src/processingTopOff.cpp \
		src/processingTimers.cpp \
		src/processingTimersv.cpp \
		src/processingTimersSec.cpp \
		src/processingEvents.cpp \
		src/processingSun.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainWindow.o src/mainWindow.cpp

obj/mainWindowAbout.o: src/mainWindowAbout.cpp src/mainWindow.h \
		src/ui_mainWindow.h \
		src/aboutDialog.h \
		src/ui_aboutDialog.h \
		src/commandProcessor.h \
		src/commandsDefs.h \
		src/command.h \
		src/tempDisplay.h \
		src/temperature.h \
		src/commonDefs.h \
		src/outDisplay.h \
		src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h \
		src/pwmSettings.h \
		src/ui_pwmSettings.h \
		src/tempSettings.h \
		src/ui_tempSettings.h \
		src/comboBoxOuts.h \
		src/main.h \
		src/timersSettings.h \
		src/ui_timersSettings.h \
		src/comboBoxWeekDay.h \
		src/timersvSettings.h \
		src/ui_timersvSettings.h \
		src/timersSecSettings.h \
		src/ui_timersSecSettings.h \
		src/codeUpdate.h \
		src/codeUpdateDialog.h \
		src/ui_codeUpdateDialog.h \
		src/codeUpdateThread.h \
		src/sunScenario.h \
		src/controlComponent.h \
		src/ui_sunScenario.h \
		src/comboBoxPwms.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainWindowAbout.o src/mainWindowAbout.cpp

obj/mainWindowUpdate.o: src/mainWindowUpdate.cpp src/mainWindow.h \
		src/ui_mainWindow.h \
		src/aboutDialog.h \
		src/ui_aboutDialog.h \
		src/commandProcessor.h \
		src/commandsDefs.h \
		src/command.h \
		src/tempDisplay.h \
		src/temperature.h \
		src/commonDefs.h \
		src/outDisplay.h \
		src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h \
		src/pwmSettings.h \
		src/ui_pwmSettings.h \
		src/tempSettings.h \
		src/ui_tempSettings.h \
		src/comboBoxOuts.h \
		src/main.h \
		src/timersSettings.h \
		src/ui_timersSettings.h \
		src/comboBoxWeekDay.h \
		src/timersvSettings.h \
		src/ui_timersvSettings.h \
		src/timersSecSettings.h \
		src/ui_timersSecSettings.h \
		src/codeUpdate.h \
		src/codeUpdateDialog.h \
		src/ui_codeUpdateDialog.h \
		src/codeUpdateThread.h \
		src/sunScenario.h \
		src/controlComponent.h \
		src/ui_sunScenario.h \
		src/comboBoxPwms.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainWindowUpdate.o src/mainWindowUpdate.cpp

obj/outDisplay.o: src/outDisplay.cpp src/outDisplay.h \
		src/main.h \
		src/commonDefs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/outDisplay.o src/outDisplay.cpp

obj/pwmSettings.o: src/pwmSettings.cpp src/pwmSettings.h \
		src/ui_pwmSettings.h \
		src/main.h \
		src/commonDefs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/pwmSettings.o src/pwmSettings.cpp

obj/outSettings.o: src/outSettings.cpp src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h \
		src/commonDefs.h \
		src/main.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/outSettings.o src/outSettings.cpp

obj/refreshThread.o: src/refreshThread.cpp src/refreshThread.h \
		src/codeUpdate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/refreshThread.o src/refreshThread.cpp

obj/tempDisplay.o: src/tempDisplay.cpp src/tempDisplay.h \
		src/temperature.h \
		src/commonDefs.h \
		src/main.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tempDisplay.o src/tempDisplay.cpp

obj/temperature.o: src/temperature.cpp src/temperature.h \
		src/commonDefs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/temperature.o src/temperature.cpp

obj/tempSettings.o: src/tempSettings.cpp src/tempSettings.h \
		src/temperature.h \
		src/commonDefs.h \
		src/ui_tempSettings.h \
		src/comboBoxOuts.h \
		src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h \
		src/main.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tempSettings.o src/tempSettings.cpp

obj/timersSettings.o: src/timersSettings.cpp src/timersSettings.h \
		src/ui_timersSettings.h \
		src/comboBoxWeekDay.h \
		src/comboBoxOuts.h \
		src/commonDefs.h \
		src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/timersSettings.o src/timersSettings.cpp

obj/timersvSettings.o: src/timersvSettings.cpp src/timersvSettings.h \
		src/ui_timersvSettings.h \
		src/comboBoxOuts.h \
		src/commonDefs.h \
		src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/timersvSettings.o src/timersvSettings.cpp

obj/comboBoxQButtons.o: src/comboBoxQButtons.cpp src/comboBoxQButtons.h \
		src/commonDefs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/comboBoxQButtons.o src/comboBoxQButtons.cpp

obj/timersSecSettings.o: src/timersSecSettings.cpp src/timersSecSettings.h \
		src/ui_timersSecSettings.h \
		src/comboBoxWeekDay.h \
		src/comboBoxOuts.h \
		src/commonDefs.h \
		src/outSettings.h \
		src/ui_outSettings.h \
		src/comboBoxQButtons.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/timersSecSettings.o src/timersSecSettings.cpp

obj/sunScenario.o: src/sunScenario.cpp src/sunScenario.h \
		src/controlComponent.h \
		src/ui_sunScenario.h \
		src/comboBoxPwms.h \
		src/commonDefs.h \
		src/pwmSettings.h \
		src/ui_pwmSettings.h \
		src/main.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/sunScenario.o src/sunScenario.cpp

obj/controlComponent.o: src/controlComponent.cpp src/controlComponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/controlComponent.o src/controlComponent.cpp

obj/comboBoxPwms.o: src/comboBoxPwms.cpp src/comboBoxPwms.h \
		src/commonDefs.h \
		src/pwmSettings.h \
		src/ui_pwmSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/comboBoxPwms.o src/comboBoxPwms.cpp

obj/moc_aboutDialog.o: obj/moc_aboutDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_aboutDialog.o obj/moc_aboutDialog.cpp

obj/moc_codeUpdateThread.o: obj/moc_codeUpdateThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_codeUpdateThread.o obj/moc_codeUpdateThread.cpp

obj/moc_codeUpdateDialog.o: obj/moc_codeUpdateDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_codeUpdateDialog.o obj/moc_codeUpdateDialog.cpp

obj/moc_comboBoxOuts.o: obj/moc_comboBoxOuts.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_comboBoxOuts.o obj/moc_comboBoxOuts.cpp

obj/moc_comboBoxWeekDay.o: obj/moc_comboBoxWeekDay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_comboBoxWeekDay.o obj/moc_comboBoxWeekDay.cpp

obj/moc_commandProcessor.o: obj/moc_commandProcessor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_commandProcessor.o obj/moc_commandProcessor.cpp

obj/moc_mainWindow.o: obj/moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mainWindow.o obj/moc_mainWindow.cpp

obj/moc_outDisplay.o: obj/moc_outDisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_outDisplay.o obj/moc_outDisplay.cpp

obj/moc_outSettings.o: obj/moc_outSettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_outSettings.o obj/moc_outSettings.cpp

obj/moc_refreshThread.o: obj/moc_refreshThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_refreshThread.o obj/moc_refreshThread.cpp

obj/moc_tempDisplay.o: obj/moc_tempDisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_tempDisplay.o obj/moc_tempDisplay.cpp

obj/moc_tempSettings.o: obj/moc_tempSettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_tempSettings.o obj/moc_tempSettings.cpp

obj/moc_timersSettings.o: obj/moc_timersSettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_timersSettings.o obj/moc_timersSettings.cpp

obj/moc_timersvSettings.o: obj/moc_timersvSettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_timersvSettings.o obj/moc_timersvSettings.cpp

obj/moc_comboBoxQButtons.o: obj/moc_comboBoxQButtons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_comboBoxQButtons.o obj/moc_comboBoxQButtons.cpp

obj/moc_pwmSettings.o: obj/moc_pwmSettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_pwmSettings.o obj/moc_pwmSettings.cpp

obj/moc_sunScenario.o: obj/moc_sunScenario.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_sunScenario.o obj/moc_sunScenario.cpp

obj/moc_timersSecSettings.o: obj/moc_timersSecSettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_timersSecSettings.o obj/moc_timersSecSettings.cpp

obj/moc_controlComponent.o: obj/moc_controlComponent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_controlComponent.o obj/moc_controlComponent.cpp

obj/moc_comboBoxPwms.o: obj/moc_comboBoxPwms.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_comboBoxPwms.o obj/moc_comboBoxPwms.cpp

obj/qrc_aquamatcontrol.o: resources/qrc_aquamatcontrol.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_aquamatcontrol.o resources/qrc_aquamatcontrol.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

